exports.temple = `/* Automatic generated by './build/build-routes-entry.js' */
{{include}}

const routes = [
  {
    path: '/login',
    component: Login,
    name: 'login',
    hidden: true,
  },
  {
    path: '/home',
    component: Home,
    name: 'home',
    hidden: true,
  },
  {
    path: '/',
    redirect: '/hello',
    component: Home,
    name: 'hello',
    menuName: '进入Pyff',
    iconCls: 'py-icon-message', // 图标样式class
    children: [
      { path: '/hello', component: HelloworldHello, name: 'helloWorld', menuName: '欢迎使用' },
    ],
  },
  {
    path: '/report',
    redirect: 'reportlist',
    component: Home,
    name: 'reportCenter',
    menuName: '报表中心',
    iconCls: 'fa fa-book fa-fw', // 图标样式class
    children: [
      { path: '/reportlist', component: ReportReport, name: 'report', menuName: '报表中心' },
      { path: '/userlist', component: Unopened, name: 'userlist', menuName: '用户列表' },
    ],
  },
  {
    path: '/404',
    component: NotFound,
    name: 'notFound',
    hidden: true,
  },
  {
    path: '/unopened',
    component: Unopened,
    name: 'unopened',
    hidden: true,
  },
  {
    path: '*',
    hidden: true,
    redirect: { path: '/404' },
  },
];

export default routes;

`;

