/* Automatic generated by './build/build-routes-entry.js' */
import NotFound from './views/404.vue';
import Home from './views/Home.vue';
import Login from './views/Login.vue';
import Main from './views/Main.vue';
import Unopened from './views/Unopened.vue';
import HelloworldHello from './views/helloworld/hello.vue';
import ReportReport from './views/report/report.vue';

const routes = [
  {
    path: '/login',
    component: Login,
    name: 'login',
    hidden: true,
  },
  {
    path: '/home',
    component: Home,
    name: 'home',
    hidden: true,
  },
  {
    path: '/',
    component: Home,
    name: 'hello',
    menuName: '进入Pyff',
    iconCls: 'py-icon-message', // 图标样式class
    children: [
      { path: '/hello', component: HelloworldHello, name: 'helloWorld', menuName: '欢迎使用' },
    ],
  },
  {
    path: '/report',
    component: Home,
    name: 'reportCenter',
    menuName: '报表中心',
    iconCls: 'fa fa-book fa-fw', // 图标样式class
    children: [
      { path: '/report', component: ReportReport, name: 'report', menuName: '报表中心' },
    ],
  },
  {
    path: '/404',
    component: NotFound,
    name: 'notFound',
    hidden: true,
  },
  {
    path: '/unopened',
    component: Unopened,
    name: 'unopened',
    hidden: true,
  },
  {
    path: '*',
    hidden: true,
    redirect: { path: '/404' },
  },
];

export default routes;

