/* Automatic generated by './build/build-routes-entry.js' */
import NotFound from './views/404.vue';
import Home from './views/Home.vue';
import Login from './views/Login.vue';
import Main from './views/Main.vue';
import Unopened from './views/Unopened.vue';
import HelloworldHello from './views/helloworld/hello.vue';

const routes = [
  {
    path: '/login',
    component: Login,
    name: 'login',
    hidden: true,
  },
  {
    path: '/',
    component: HelloworldHello,
    name: 'hello',
    iconCls: 'py-icon-message', // 图标样式class
  },
  {
    path: '/404',
    component: NotFound,
    name: 'notFound',
    hidden: true,
  },
  {
    path: '/unopened',
    component: Unopened,
    name: 'unopened',
    hidden: true,
  },
  {
    path: '*',
    hidden: true,
    redirect: { path: '/404' },
  },
];

export default routes;

